### ISSUE TITLE
`stb serve` fails on Windows

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/sphinx-theme-builder#10]
https://github.com/pradyunsg/furo/discussions/322#discussioncomment-1908398

**Comment by john-hen** [comment]
Out of curiosity, I looked into this a bit more. Might have considered a PR, but I find this really difficult to test what with the problem being split across three projects, and there's all these separate virtual environments involved.

When `nox -s docs-live` is run for Furo, then `stb serve docs/` ends up passing `--pre-build` as well as `--re-ignore` command-line options to Sphinx-Autobuild.

https://github.com/pradyunsg/sphinx-theme-builder/blob/65017fdec3ca749b70434f2d04271e1c99bedb53/src/sphinx_theme_builder/_internal/cli/serve.py#L74-L88

When Sphinx-Autobuild receives the pre-build command(s), it applies `shlex.split`.

https://github.com/executablebooks/sphinx-autobuild/blob/1eb7d7746b773f515de64f1bd83c14bccca8a1ef/src/sphinx_autobuild/cli.py#L34

That's how the path separators disappear on Windows.
```console
>>> import shlex, sys
>>> sys.executable
'C:\\temp\\envs\\test\\Scripts\\python.exe'
>>> shlex.split(f"{sys.executable} - m sphinx_theme_builder compile")
['C:tempenvstestScriptspython.exe', '-', 'm', 'sphinx_theme_builder', 'compile']
```

I think (and this [Stack Overflow answer] agrees) it's best to just skip calling `shlex.split` there when on Windows. Though it would also help to put the command in nested quotes, which would solve the problem on the caller side:
```console
>>> shlex.split(f"'{sys.executable}' - m sphinx_theme_builder compile")
['C:\\temp\\envs\\test\\Scripts\\python.exe', '-', 'm', 'sphinx_theme_builder', 'compile']
```

There's another issue though, with the pipe characters in the regular expression of `re-ignore`. On Windows, they need to be escaped with a caret, so `'^|'.join` instead of `'|'.join`.

[Stack Overflow answer]: https://stackoverflow.com/a/35900070

**Comment by pradyunsg** [comment]
Ah! Fun! I really appreciate you digging into this @john-hen! ^.^

> On Windows, they need to be escaped with a caret, so `'^|'.join` instead of `'|'.join`.

That should be handled by subprocess, as I understand it.

---

Since you have a Windows machine, can you try the following:

- Get a clean clone of Furo and a clean venv.
- `pip install "sphinx-theme-builder[cli] @ https://github.com/pradyunsg/sphinx-theme-builder/archive/refs/heads/main.zip"`
- `pip install -e ".[docs]"`
- `stb serve docs/`

**Comment by john-hen** [comment]
Yes, that works. 👍 

I stand corrected on the caret thing then. Could have sworn I needed that when I tried the same thing earlier, just adding the single quotes. But I had hacked the STB copy in Furo's `.nox` venv, so probably got mislead by something in the process.

**Comment by pradyunsg** [comment]
Closing this out, based on https://github.com/pradyunsg/sphinx-theme-builder/issues/10#ref-commit-97bd61c then!

**Comment by pradyunsg** [comment]
I'll cut a release when I have some free time.
